resources:
  repositories:
    - repository: self
      trigger: none

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      name: 'Default'
    steps:
    - checkout: self

    # Task mta' el Replace Tokens (Hédhi dima khalliha khaterha salla7t el secret)
    - task: qetza.replacetokens.replacetokens-task.replacetokens@5
      displayName: 'Replace Tokens in Constants.cs'
      inputs:
        targetFiles: '**/Constants.cs'
        encoding: 'auto'
        tokenPattern: 'custom'
        tokenPrefix: '#{' 
        tokenSuffix: '}#' 
        verbosity: 'detailed' 
        keepToken: false

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: 'tests/UnitTests/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-o $(Build.ArtifactStagingDirectory)'
    
    # --- Artifacts: Hna l'fayda mta' el Lab ---
    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts ADO - Website
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'Website'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts ADO - Bicep
      inputs:
        targetPath: '$(Build.SourcesDirectory)/eShopOnWeb-main/infra/webapp.bicep' 
        artifact: 'Bicep'
        publishLocation: 'pipeline'